### ISSUE TITLE
List text look different from the rest of the content

### ISSUE THREAD

**Issue by Hjdskes** [mtn/cocoa-eh-hugo-theme#13]
This picture shows how the text is smaller and has a different color.

![screenshot from 2017-02-25 18-23-29](https://cloud.githubusercontent.com/assets/1260727/23333184/8b7be584-fb87-11e6-9e31-bbd0934303aa.png)

I fixed this by adding the following to the css, but there might be a better way to fix this.

```css
section.main .content .markdown ul,
section.main .content .markdown ol,
section.main .content .markdown dl {
  margin-bottom: 1rem;
  color: #313537;
  font-size: 1.2em;
  letter-spacing: 0.01rem;
  font-family: 'Source Sans Pro', sans-serif;
  font-weight: 100;
  text-align: justify;
}
```
